/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SignFrame;

import SignFrame.DangKy;
import javax.swing.JOptionPane;
import menuFrame.menu;
import modelUser.ConnectUser;
import modelUser.ListUser;
import modelUser.User;

/**
 *
 * @author ADMIN
 */
public class signUp extends javax.swing.JFrame {

    ListUser listUser=new ListUser();
    public signUp() {
        initComponents();
        this.setTitle("Đăng Nhập");
        this.setLocationRelativeTo(null);
        listUser.reset();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        componentMoverUtil1 = new com.k33ptoo.utils.ComponentMoverUtil();
        componentMoverUtil2 = new com.k33ptoo.utils.ComponentMoverUtil();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        TextTaiKhoan = new javax.swing.JTextField();
        TextMatKhau = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bDangKy = new com.k33ptoo.components.KButton();
        nDangNhap = new com.k33ptoo.components.KButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setInheritsPopupMenu(true);
        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));

        TextTaiKhoan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        TextTaiKhoan.setOpaque(false);

        TextMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        TextMatKhau.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 255));
        jLabel1.setText("ĐĂNG NHẬP");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/People-Patient-Male-icon.png"))); // NOI18N
        jLabel2.setText("username");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/key-lock-icon.png"))); // NOI18N
        jLabel3.setText("password");

        bDangKy.setText("Sign up");
        bDangKy.setkBackGroundColor(new java.awt.Color(51, 255, 255));
        bDangKy.setkBorderRadius(25);
        bDangKy.setkEndColor(new java.awt.Color(153, 51, 255));
        bDangKy.setkHoverForeGround(new java.awt.Color(0, 204, 255));
        bDangKy.setkHoverStartColor(new java.awt.Color(0, 204, 255));
        bDangKy.setkSelectedColor(new java.awt.Color(0, 204, 51));
        bDangKy.setkStartColor(new java.awt.Color(204, 0, 255));
        bDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDangKyActionPerformed(evt);
            }
        });

        nDangNhap.setText("Sign in");
        nDangNhap.setkBackGroundColor(new java.awt.Color(51, 255, 255));
        nDangNhap.setkBorderRadius(25);
        nDangNhap.setkEndColor(new java.awt.Color(51, 255, 255));
        nDangNhap.setkHoverForeGround(new java.awt.Color(0, 204, 255));
        nDangNhap.setkHoverStartColor(new java.awt.Color(0, 204, 255));
        nDangNhap.setkSelectedColor(new java.awt.Color(0, 204, 51));
        nDangNhap.setkStartColor(new java.awt.Color(204, 0, 204));
        nDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nDangNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(nDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(bDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextTaiKhoan)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(TextMatKhau))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nDangNhapActionPerformed
        if(emptyLogin())
            JOptionPane.showMessageDialog(this, "Chua Nhap Tai Khoan Hoac Mat Khau!");
        else{
            if(valueLogin()){
                System.out.println(getUser());
                new menu().setVisible(true);
                this.dispose();
                        
            }
            else{
                JOptionPane.showMessageDialog(this, "Tai Khoan Hoac Mat Khau Khong Dung!");
            }
        }
    }//GEN-LAST:event_nDangNhapActionPerformed

    private void bDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDangKyActionPerformed
        
        this.dispose();
        new DangKy().setVisible(true);
    }//GEN-LAST:event_bDangKyActionPerformed

    public boolean emptyLogin(){
        String taikhoan=TextTaiKhoan.getText();
        String matkhau=TextMatKhau.getText();
        if(taikhoan.isEmpty() || matkhau.isEmpty())
            return true;
        return false;
    }
    public boolean valueLogin(){
        String taikhoan=TextTaiKhoan.getText();
        String matkhau=new String(TextMatKhau.getPassword());
        ListUser x=new ListUser();
        if(x.checkLogin(taikhoan, matkhau))
            return true;
        return false;
    }
    public User getUser(){
        String taikhoan=TextTaiKhoan.getText();
        String matkhau=new String (TextMatKhau.getPassword());
        for(User u:listUser.getAllUser()){
            if(u.getTaikhoan().equals(taikhoan) && u.getMatkhau().equals(matkhau)){
                u.setCheckOnline(1);
                ConnectUser.Update(u);
                return u;
            }
                
            
        }
        return null;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUp().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TextMatKhau;
    private javax.swing.JTextField TextTaiKhoan;
    private com.k33ptoo.components.KButton bDangKy;
    private com.k33ptoo.utils.ComponentMoverUtil componentMoverUtil1;
    private com.k33ptoo.utils.ComponentMoverUtil componentMoverUtil2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KButton nDangNhap;
    // End of variables declaration//GEN-END:variables
}
