/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menuFrame;

import BanHang.BanHang;
import BanHang.ListBanHang;
import DienThoaiModel.ConnectDT;
import DienThoaiModel.DienThoai;
import DienThoaiModel.ListDienThoai;
import DienThoaiModel.ListHangDienThoai;
import KhachHangModel.KhachHang;
import KhachHangModel.ListKhachHang;
import NhanVienModel.ConnectNV;
import NhanVienModel.NhanVien;
import NhanVienModel.NhanVienDao;
import SignFrame.DangKy;
import SignFrame.signUp;
import TestChart.BarChart;
import static TestChart.BarChart.createChart;
import static TestChart.BarChart.createDataset;
import static TestChart.TestPieChart.createDataset;
import static TestChart.TestPieChart.createPieChart;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelUser.ListUser;
import modelUser.User;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;

/**
 *
 * @author ADMIN
 */
public class menu extends javax.swing.JFrame {
    SimpleDateFormat date_format = new SimpleDateFormat("dd/MM/yyyy");
    String strHinhAnh=null;
    ListKhachHang listKh=new ListKhachHang();
    NhanVienDao listNv=new NhanVienDao();
    ListDienThoai list=new ListDienThoai();
    ListHangDienThoai listHang=new ListHangDienThoai();
    ListUser listUser=new ListUser();
    ListBanHang listBh=new ListBanHang();
    public menu() {
        initComponents();
        showComboHang2();
        jPBanHang.setVisible(true);
        jPDienThoai.setVisible(false);
        jPCapNhat.setVisible(false);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMenu = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        kButton6 = new com.k33ptoo.components.KButton();
        kButton7 = new com.k33ptoo.components.KButton();
        kButton8 = new com.k33ptoo.components.KButton();
        kButton9 = new com.k33ptoo.components.KButton();
        kbDangXuat = new com.k33ptoo.components.KButton();
        TabMenu = new javax.swing.JTabbedPane();
        quanlydienthoai = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        kbBanHang = new com.k33ptoo.components.KButton();
        kbHoaDon = new com.k33ptoo.components.KButton();
        kbsanpham = new com.k33ptoo.components.KButton();
        jPanel7 = new javax.swing.JPanel();
        jPCapNhat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtKhachHang = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        TextNhapTen = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jcSapXep = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jbTimKiem = new javax.swing.JButton();
        jPBanHang = new javax.swing.JPanel();
        TextGia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcBaoHanh = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextTra = new javax.swing.JTextField();
        TextDu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcTen = new javax.swing.JComboBox<>();
        TextSoLuong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TextHang = new javax.swing.JTextField();
        jbTim = new javax.swing.JButton();
        jbLuuThongTin = new javax.swing.JButton();
        TextTenKhachHang = new javax.swing.JTextField();
        TextSDT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TextDiaChi = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jDate = new com.toedter.calendar.JDateChooser();
        jlThongTin = new javax.swing.JLabel();
        jPDienThoai = new javax.swing.JPanel();
        TextMa2 = new javax.swing.JTextField();
        TextTen2 = new javax.swing.JTextField();
        TextGia2 = new javax.swing.JTextField();
        TextSoLuong2 = new javax.swing.JTextField();
        TextTong2 = new javax.swing.JTextField();
        jcHang2 = new javax.swing.JComboBox<>();
        hinhanh2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtDienThoai2 = new javax.swing.JTable();
        jbThem = new javax.swing.JButton();
        jbXoa = new javax.swing.JButton();
        jbSua = new javax.swing.JButton();
        jPNhanVien = new javax.swing.JPanel();
        TextTenNhanVien = new javax.swing.JTextField();
        TextMnv = new javax.swing.JTextField();
        TextNgaySinh = new javax.swing.JTextField();
        jcGioiTinh = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtNhanVien = new javax.swing.JTable();
        TextQueQuan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TextLuong = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        anhnhanvien = new javax.swing.JLabel();
        jbLuu = new javax.swing.JButton();
        jbXoaNv = new javax.swing.JButton();
        jvSuanv = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TextSoDienThoai = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPThongKe = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtDoanhThu = new javax.swing.JTable();
        jlTongDienThoai = new javax.swing.JLabel();
        tlTongDoanhThu = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(920, 660));

        jPMenu.setMinimumSize(new java.awt.Dimension(810, 600));
        jPMenu.setPreferredSize(new java.awt.Dimension(800, 600));
        jPMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(204, 255, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("    MENU");

        kButton6.setText("Quản lý sản phẩm");
        kButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kButton6.setkEndColor(new java.awt.Color(0, 153, 204));
        kButton6.setkStartColor(new java.awt.Color(204, 204, 255));
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });

        kButton7.setText("Quản lý nhân viên");
        kButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kButton7.setkEndColor(new java.awt.Color(0, 153, 204));
        kButton7.setkStartColor(new java.awt.Color(204, 204, 255));
        kButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton7ActionPerformed(evt);
            }
        });

        kButton8.setText("Doanh thu");
        kButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kButton8.setkEndColor(new java.awt.Color(0, 153, 204));
        kButton8.setkStartColor(new java.awt.Color(204, 204, 255));
        kButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton8ActionPerformed(evt);
            }
        });

        kButton9.setText("Công cụ ");
        kButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kButton9.setkEndColor(new java.awt.Color(0, 153, 204));
        kButton9.setkStartColor(new java.awt.Color(204, 204, 255));
        kButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton9ActionPerformed(evt);
            }
        });

        kbDangXuat.setText("Đăng xuất");
        kbDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kbDangXuat.setkEndColor(new java.awt.Color(255, 102, 102));
        kbDangXuat.setkStartColor(new java.awt.Color(255, 102, 102));
        kbDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addComponent(kButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addComponent(kbDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kbDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPMenu.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 600));

        quanlydienthoai.setBackground(new java.awt.Color(255, 255, 255));
        quanlydienthoai.setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(621, 105));

        kbBanHang.setText("Bán Hàng");
        kbBanHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kbBanHang.setkBackGroundColor(new java.awt.Color(255, 51, 204));
        kbBanHang.setkEndColor(new java.awt.Color(255, 204, 153));
        kbBanHang.setkHoverForeGround(new java.awt.Color(0, 255, 255));
        kbBanHang.setkStartColor(new java.awt.Color(153, 102, 255));
        kbBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbBanHangActionPerformed(evt);
            }
        });

        kbHoaDon.setText("Hóa Đơn");
        kbHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kbHoaDon.setkBackGroundColor(new java.awt.Color(0, 204, 204));
        kbHoaDon.setkEndColor(new java.awt.Color(255, 102, 153));
        kbHoaDon.setkHoverEndColor(new java.awt.Color(255, 204, 204));
        kbHoaDon.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        kbHoaDon.setkStartColor(new java.awt.Color(153, 153, 255));
        kbHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbHoaDonActionPerformed(evt);
            }
        });

        kbsanpham.setText("Sản Phẩm");
        kbsanpham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kbsanpham.setkEndColor(new java.awt.Color(255, 204, 102));
        kbsanpham.setkStartColor(new java.awt.Color(153, 153, 255));
        kbsanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbsanphamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(kbBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(kbHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(kbsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kbsanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(kbHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(kbBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        jPCapNhat.setBackground(new java.awt.Color(204, 204, 255));
        jPCapNhat.setPreferredSize(new java.awt.Dimension(600, 460));

        jtKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "Địa chỉ", "SĐT", "Tên điện thoại", "Hãng", "Bảo Hành", "Thành tiền", "Thời gian", "Số Luọng"
            }
        ));
        jScrollPane1.setViewportView(jtKhachHang);

        jLabel6.setText("                Thông Tin Khách Hàng");

        jLabel19.setText("Nhập Tên");

        jcSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên", "Tên điện thoại", "Tiền" }));

        jLabel20.setText("Sắp xếp");

        jButton1.setText("Click");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Export");

        jbTimKiem.setText("Tìm kiếm");
        jbTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCapNhatLayout = new javax.swing.GroupLayout(jPCapNhat);
        jPCapNhat.setLayout(jPCapNhatLayout);
        jPCapNhatLayout.setHorizontalGroup(
            jPCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCapNhatLayout.createSequentialGroup()
                .addGroup(jPCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCapNhatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                    .addGroup(jPCapNhatLayout.createSequentialGroup()
                        .addGroup(jPCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCapNhatLayout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPCapNhatLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPCapNhatLayout.createSequentialGroup()
                                        .addComponent(TextNhapTen, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbTimKiem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22)))
                .addContainerGap())
            .addGroup(jPCapNhatLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPCapNhatLayout.setVerticalGroup(
            jPCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCapNhatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(15, 15, 15)
                .addGroup(jPCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextNhapTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jbTimKiem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(199, 199, 199))
        );

        jPBanHang.setBackground(new java.awt.Color(204, 204, 255));
        jPBanHang.setPreferredSize(new java.awt.Dimension(600, 400));

        TextGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextGiaActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên điện thoại");

        jLabel3.setText("Giá");

        jcBaoHanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 năm", "2 năm", "3 năm", "4 năm" }));
        jcBaoHanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBaoHanhActionPerformed(evt);
            }
        });

        jLabel4.setText("Bảo hành");

        jLabel5.setText("Hãng");

        TextTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextTraMouseExited(evt);
            }
        });
        TextTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTraActionPerformed(evt);
            }
        });

        TextDu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDuActionPerformed(evt);
            }
        });

        jLabel7.setText("Khách trả");

        jLabel8.setText("Tiền dư");

        jcTen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jcTenMouseEntered(evt);
            }
        });
        jcTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTenActionPerformed(evt);
            }
        });

        jLabel10.setText("Số lượng");

        jbTim.setText("Tìm");
        jbTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTimActionPerformed(evt);
            }
        });

        jbLuuThongTin.setText("Lưu thông tin");
        jbLuuThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLuuThongTinActionPerformed(evt);
            }
        });

        jLabel9.setText("Tên Khách Hàng");

        jLabel17.setText("SDT");

        jLabel18.setText("Địa chỉ");

        jLabel21.setText("Ngày");

        jlThongTin.setText("Thông tin điện thoại: ");

        javax.swing.GroupLayout jPBanHangLayout = new javax.swing.GroupLayout(jPBanHang);
        jPBanHang.setLayout(jPBanHangLayout);
        jPBanHangLayout.setHorizontalGroup(
            jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBanHangLayout.createSequentialGroup()
                .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPBanHangLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPBanHangLayout.createSequentialGroup()
                                .addComponent(TextHang, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jbTim, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jcBaoHanh, javax.swing.GroupLayout.Alignment.LEADING, 0, 129, Short.MAX_VALUE)
                                .addComponent(TextGia, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextSoLuong, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcTen, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextSDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextTenKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextTra, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPBanHangLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPBanHangLayout.createSequentialGroup()
                                .addComponent(jbLuuThongTin)
                                .addGap(62, 62, 62)
                                .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextDu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPBanHangLayout.createSequentialGroup()
                                .addComponent(jlThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))))
                .addGap(118, 118, 118))
        );
        jPBanHangLayout.setVerticalGroup(
            jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5))
                .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBanHangLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)
                        .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPBanHangLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(TextSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel3)))
                            .addGroup(jPBanHangLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPBanHangLayout.createSequentialGroup()
                                .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)))
                            .addComponent(TextGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPBanHangLayout.createSequentialGroup()
                        .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPBanHangLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TextHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbTim, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPBanHangLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(TextTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(58, 58, 58)
                        .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel18))
                        .addGap(4, 4, 4)
                        .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcBaoHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbLuuThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextDu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPDienThoai.setBackground(new java.awt.Color(204, 204, 255));
        jPDienThoai.setPreferredSize(new java.awt.Dimension(600, 460));
        jPDienThoai.setVerifyInputWhenFocusTarget(false);

        hinhanh2.setText("               Ảnh");
        hinhanh2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hinhanh2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hinhanh2MouseClicked(evt);
            }
        });

        jLabel26.setText("Mã điện thoại");

        jLabel27.setText("Tên điện thoại");

        jLabel28.setText("Giá điện thoại");

        jLabel29.setText("Hãng điện thoại");

        jLabel30.setText("Số lượng");

        jLabel31.setText("Tổng");

        jtDienThoai2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Hãng", "Giá", "Số lượng", "Hình Ảnh"
            }
        ));
        jtDienThoai2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDienThoai2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtDienThoai2);

        jbThem.setText("Thêm");
        jbThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbThemActionPerformed(evt);
            }
        });

        jbXoa.setText("Xóa");
        jbXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbXoaActionPerformed(evt);
            }
        });

        jbSua.setText("Sửa");
        jbSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPDienThoaiLayout = new javax.swing.GroupLayout(jPDienThoai);
        jPDienThoai.setLayout(jPDienThoaiLayout);
        jPDienThoaiLayout.setHorizontalGroup(
            jPDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDienThoaiLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDienThoaiLayout.createSequentialGroup()
                        .addGroup(jPDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TextGia2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextMa2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel26)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TextTen2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextSoLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel27)
                            .addComponent(jLabel30))
                        .addGap(35, 35, 35)
                        .addGroup(jPDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextTong2)
                                .addComponent(jcHang2, 0, 97, Short.MAX_VALUE)
                                .addComponent(jLabel29))))
                    .addGroup(jPDienThoaiLayout.createSequentialGroup()
                        .addComponent(jbThem, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jbXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jbSua, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hinhanh2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane4)
        );
        jPDienThoaiLayout.setVerticalGroup(
            jPDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDienThoaiLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDienThoaiLayout.createSequentialGroup()
                        .addGroup(jPDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29))
                        .addGap(2, 2, 2)
                        .addGroup(jPDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextMa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextTen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcHang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(3, 3, 3)
                        .addGroup(jPDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextGia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextSoLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextTong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbThem)
                            .addComponent(jbXoa)
                            .addComponent(jbSua)))
                    .addComponent(hinhanh2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout quanlydienthoaiLayout = new javax.swing.GroupLayout(quanlydienthoai);
        quanlydienthoai.setLayout(quanlydienthoaiLayout);
        quanlydienthoaiLayout.setHorizontalGroup(
            quanlydienthoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, quanlydienthoaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(quanlydienthoaiLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        quanlydienthoaiLayout.setVerticalGroup(
            quanlydienthoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quanlydienthoaiLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabMenu.addTab("Điện thoại", quanlydienthoai);

        jPNhanVien.setBackground(new java.awt.Color(204, 204, 255));

        jcGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jtNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "mnv", "Tên", "Ngày sinh", "quê quán", "giới tính", "lương", "hình ảnh", "SDT"
            }
        ));
        jtNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtNhanVien);

        jLabel11.setText("Tên nhân viên");

        jLabel12.setText("Mã nhân viên");

        jLabel13.setText("Ngày sinh");

        jLabel14.setText("Quê Quán");

        jLabel15.setText("Lương cơ bản");

        jLabel16.setText("Giới tính");

        anhnhanvien.setText("                   Ảnh");
        anhnhanvien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        anhnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anhnhanvienMouseClicked(evt);
            }
        });

        jbLuu.setText("Lưu");
        jbLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLuuActionPerformed(evt);
            }
        });

        jbXoaNv.setText("Xóa");
        jbXoaNv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbXoaNvActionPerformed(evt);
            }
        });

        jvSuanv.setText("Sửa");
        jvSuanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvSuanvActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Tài khoản nhân viên");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel22.setText("SDT");

        javax.swing.GroupLayout jPNhanVienLayout = new javax.swing.GroupLayout(jPNhanVien);
        jPNhanVien.setLayout(jPNhanVienLayout);
        jPNhanVienLayout.setHorizontalGroup(
            jPNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPNhanVienLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNhanVienLayout.createSequentialGroup()
                        .addGroup(jPNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPNhanVienLayout.createSequentialGroup()
                                .addComponent(jbLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jbXoaNv, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jvSuanv, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPNhanVienLayout.createSequentialGroup()
                                .addGroup(jPNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(78, 78, 78)
                                .addGroup(jPNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))
                            .addGroup(jPNhanVienLayout.createSequentialGroup()
                                .addGroup(jPNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextQueQuan, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                        .addComponent(TextTenNhanVien)
                                        .addComponent(TextMnv)
                                        .addComponent(TextNgaySinh))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(109, 109, 109)
                                .addComponent(anhnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPNhanVienLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPNhanVienLayout.createSequentialGroup()
                        .addGroup(jPNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPNhanVienLayout.setVerticalGroup(
            jPNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPNhanVienLayout.createSequentialGroup()
                        .addComponent(TextTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(4, 4, 4)
                        .addComponent(TextMnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(5, 5, 5)
                        .addComponent(TextNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(anhnhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(2, 2, 2)
                .addGroup(jPNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLuu)
                    .addComponent(jbXoaNv)
                    .addComponent(jvSuanv))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TabMenu.addTab("Nhân Viên", jPNhanVien);

        jPThongKe.setBackground(new java.awt.Color(255, 204, 204));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel23.setText("THỐNG KÊ DOANH THU THEO HÃNG ĐIỆN THOẠI");

        jButton4.setText("Biểu đồ số lượng");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jtDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Hãng", "Số Lượng", "Doanh Thu"
            }
        ));
        jtDoanhThu.setAlignmentX(2.0F);
        jtDoanhThu.setAlignmentY(2.0F);
        jtDoanhThu.setRowHeight(25);
        jScrollPane3.setViewportView(jtDoanhThu);

        jlTongDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlTongDienThoai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlTongDienThoai.setPreferredSize(new java.awt.Dimension(41, 20));

        tlTongDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tlTongDoanhThu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tlTongDoanhThu.setPreferredSize(new java.awt.Dimension(41, 20));

        jButton6.setText("Biểu đồ doanh thu");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPThongKeLayout = new javax.swing.GroupLayout(jPThongKe);
        jPThongKe.setLayout(jPThongKeLayout);
        jPThongKeLayout.setHorizontalGroup(
            jPThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPThongKeLayout.createSequentialGroup()
                .addGroup(jPThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPThongKeLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel23))
                    .addGroup(jPThongKeLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPThongKeLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(jPThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlTongDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                            .addComponent(tlTongDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPThongKeLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jButton4)
                        .addGap(142, 142, 142)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPThongKeLayout.setVerticalGroup(
            jPThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPThongKeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jlTongDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(tlTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        TabMenu.addTab("Doanh Thu", jPThongKe);

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        TabMenu.addTab("Công Cụ", jPanel6);

        jPMenu.add(TabMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -30, 700, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        TabMenu.setSelectedIndex(3);
        fillTable();
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kbBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbBanHangActionPerformed
        jPDienThoai.setVisible(false);
        jPCapNhat.setVisible(false);
        jPBanHang.setVisible(true);  
    }//GEN-LAST:event_kbBanHangActionPerformed

    private void kbCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbCapNhatActionPerformed
        
    }//GEN-LAST:event_kbCapNhatActionPerformed

    private void kbDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbDienThoaiActionPerformed
 
    }//GEN-LAST:event_kbDienThoaiActionPerformed
    
    private void hinhanh2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hinhanh2MouseClicked
        JFileChooser jfc = new JFileChooser();
        jfc.showOpenDialog(null);
        File file = jfc.getSelectedFile();
       
        strHinhAnh=file.getAbsolutePath();
        if(strHinhAnh!=null){
            hinhanh2.setIcon(ResizeImage(String.valueOf(strHinhAnh)));
        
        }
        else{
            hinhanh2.setIcon(null);
            hinhanh2.setText("No avatar");
        }
        
    }//GEN-LAST:event_hinhanh2MouseClicked
    public ImageIcon ResizeImage(String ImagePath){
        ImageIcon ima=new ImageIcon(ImagePath);
        Image img=ima.getImage();
        Image newImg=img.getScaledInstance(hinhanh2.getWidth(), hinhanh2.getHeight(), 0);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    private void jbThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbThemActionPerformed
        if(valiForm()){
           DienThoai dt=getModel();
           list.Add(dt);
           fillTable();
        }
        else{
            JOptionPane.showMessageDialog(this, "Ban Chua Nhap Day Du Thong Tin!");
        }
    }//GEN-LAST:event_jbThemActionPerformed

    private void jbXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbXoaActionPerformed
        String ma=TextMa2.getText();
        list.DelByMa(ma);
        DefaultTableModel table=(DefaultTableModel) jtDienThoai2.getModel();
        table.setRowCount(0);
        fillTable();
    }//GEN-LAST:event_jbXoaActionPerformed

    private void jtDienThoai2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDienThoai2MouseClicked

        int id=jtDienThoai2.rowAtPoint(evt.getPoint());
        String ma=jtDienThoai2.getValueAt(id, 0).toString();
        DienThoai dt=list.showByMa(ma);
        setModel(dt);
    }//GEN-LAST:event_jtDienThoai2MouseClicked
    
    private void TextGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextGiaActionPerformed
       
    }//GEN-LAST:event_TextGiaActionPerformed

    private void jcTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTenActionPerformed
        setGia();
    }//GEN-LAST:event_jcTenActionPerformed

    private void TextTraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextTraMouseExited
        TextDu.setText(showTienDu());
    }//GEN-LAST:event_TextTraMouseExited

    private void TextDuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDuActionPerformed

    private void anhnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anhnhanvienMouseClicked
        JFileChooser jfc = new JFileChooser();
        jfc.showOpenDialog(null);
        File file = jfc.getSelectedFile();
       
        strHinhAnh=file.getAbsolutePath();
        if(strHinhAnh!=null){
            anhnhanvien.setIcon(ResizeImageNv(String.valueOf(strHinhAnh)));
        
        }
        else{
            anhnhanvien.setIcon(null);
            anhnhanvien.setText("No avatar");
        }
        
    }//GEN-LAST:event_anhnhanvienMouseClicked
    public ImageIcon ResizeImageNv(String ImagePath){
        ImageIcon ima=new ImageIcon(ImagePath);
        Image img=ima.getImage();
        Image newImg=img.getScaledInstance(anhnhanvien.getWidth(), anhnhanvien.getHeight(), 0);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    //luu nhan vien
    private void jbLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLuuActionPerformed
        if(valiFormNv()){
            try {
                NhanVien nv=getModelNv();
                listNv.add(nv);
                fillTableNv();   
                
            } catch (ParseException ex) {
                Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Ban Chua Nhap Day Du Thong Tin!");
        }
    }//GEN-LAST:event_jbLuuActionPerformed
    
    // xoa nhan vien
    private void jbXoaNvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbXoaNvActionPerformed
        String ma=TextMnv.getText();
        String ten=TextTenNhanVien.getText();
        listNv.delByMnvVaName(ma, ten);
        DefaultTableModel table=(DefaultTableModel) jtNhanVien.getModel();
        table.setRowCount(0);
        
        fillTableNv();
        
    }//GEN-LAST:event_jbXoaNvActionPerformed

    private void jbTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTimActionPerformed
        jcTen.removeAllItems();
        String hang=TextHang.getText();
        for(DienThoai dt:list.getDienThoai()){
            if(dt.getHang().equals(hang))
                jcTen.addItem(dt.getTen());
        }
    }//GEN-LAST:event_jbTimActionPerformed

    private void TextTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTraActionPerformed

    private void jcBaoHanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBaoHanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcBaoHanhActionPerformed

    private void jbLuuThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLuuThongTinActionPerformed
        listKh.add(getModelKH());
        fillTableKH();
        DienThoai dt=list.showByName((String)jcTen.getSelectedItem());
        dt.setSoluong(dt.getSoluong()-Long.parseLong(TextSoLuong.getText()));
        ConnectDT.Update(dt);
        fillTable();
        
        
        BanHang x=new BanHang(TextHang.getText(),Long.parseLong(TextSoLuong.getText()),Long.parseLong(TextGia.getText())*Long.parseLong(TextSoLuong.getText()));
        listBh.Update(x);
        
    }//GEN-LAST:event_jbLuuThongTinActionPerformed

    private void kbHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbHoaDonActionPerformed
        jPDienThoai.setVisible(false);
        jPCapNhat.setVisible(true);
        jPBanHang.setVisible(false);
        fillTableKH();
    }//GEN-LAST:event_kbHoaDonActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        TabMenu.setSelectedIndex(0);
    }//GEN-LAST:event_kButton6ActionPerformed

    private void kButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton7ActionPerformed
        if(checkAdminOnline()){
            TabMenu.setSelectedIndex(1);
            fillTableNv();
        }
        else{
            JOptionPane.showMessageDialog(this, "Ban Khong Phai Admin");
        }
        
    }//GEN-LAST:event_kButton7ActionPerformed

    private void kButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton8ActionPerformed
        TabMenu.setSelectedIndex(2);
        fillTableThongKe();
        long tongSo=0;
        long tongTien=0;
        for(BanHang bh:listBh.getAllBanHang()){
            tongSo+=bh.getSoluong();
            tongTien+=bh.getThu();
        }
        jlTongDienThoai.setText("Tổng số điện thoại đã bán được: "+tongSo);
        tlTongDoanhThu.setText("Doanh thu: "+tongTien);
    }//GEN-LAST:event_kButton8ActionPerformed

    private void kButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton9ActionPerformed
        TabMenu.setSelectedIndex(3);
    }//GEN-LAST:event_kButton9ActionPerformed

    private void kbSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kBQuanlyActionPerformed
        
    }//GEN-LAST:event_kBQuanlyActionPerformed

    private void jcTenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcTenMouseEntered
        String dt=(String)jcTen.getSelectedItem();
        String soluong="";
        for(DienThoai x:list.getDienThoai()){
            if(x.getTen().equals(dt))
                soluong+=String.valueOf(x.getSoluong());
        }
        jlThongTin.setText("Điện thoại: "+dt+" - Số lượng: "+soluong);
    }//GEN-LAST:event_jcTenMouseEntered

    private void kbDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbDangXuatActionPerformed
        this.dispose();
        new signUp().setVisible(true);
    }//GEN-LAST:event_kbDangXuatActionPerformed
    
    public boolean checkAdminOnline(){
        for(User u:listUser.getAllUser()){
            if(u.getCheckOnline()==1 && u.getCheckAdm()==1){
                
                return true;
            }
        }
        return false;
    }
    private void kbsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbsanphamActionPerformed
        if(checkAdminOnline()){
            jPDienThoai.setVisible(true);
            fillTable();
            jPBanHang.setVisible(false);
            jPCapNhat.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(this, "Ban Khong Phai Admin");
        }
            
        
    }//GEN-LAST:event_kbsanphamActionPerformed

    private void jbSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSuaActionPerformed
        DienThoai dt=getModel();
        list.Update(dt);
        fillTable();
    }//GEN-LAST:event_jbSuaActionPerformed

    private void jvSuanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvSuanvActionPerformed
        try {
            NhanVien n=getModelNv();
            listNv.Update(n);
            
            fillTableNv();
        } catch (ParseException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jvSuanvActionPerformed

    private void jtNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtNhanVienMouseClicked
        int id=jtNhanVien.rowAtPoint(evt.getPoint());
        String ma=jtNhanVien.getValueAt(id, 0).toString();
        NhanVien nv=listNv.getNhanVienByMnv(ma);
        setModelNv(nv);
    }//GEN-LAST:event_jtNhanVienMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new TaiKhoanNhanVien().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTimKiemActionPerformed
        fillTableKHbyName();
    }//GEN-LAST:event_jbTimKiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jcSapXep.getSelectedItem().equals("Tên")){
            listKh.sortTen();
            fillTableKH();
        }
        if(jcSapXep.getSelectedItem().equals("Tên điện thoại")){
            listKh.sortTendt();
            fillTableKH();
        }
        if(jcSapXep.getSelectedItem().equals("Tiền")){
            listKh.sortTien();
            fillTableKH();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ChartPanel chartPanel = new ChartPanel(createChart());
        JFrame frame = new JFrame();
        frame.add(chartPanel);
        frame.setTitle("Biểu đồ Thống kê");
        frame.setSize(600, 400);
        frame.setLocationRelativeTo(null);
        frame.setResizable(false);
        frame.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        ChartPanel chartPanel = new ChartPanel(createPieChart());
        JFrame frame = new JFrame();
        frame.add(chartPanel);
        frame.setSize(600, 400);
        frame.setLocationRelativeTo(null);
        frame.setResizable(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed
    //// Quản Lý điện thoại
    public void reset(){
        TextMa2.setText("");
        TextTen2.setText("");
        TextSoLuong2.setText("");
        TextGia2.setText("");
        TextTong2.setText("");
        hinhanh2.setIcon(null);
    }
    public void setModel(DienThoai dt){
        TextMa2.setText(dt.getMa());
        TextTen2.setText(dt.getTen());
        TextSoLuong2.setText(String.valueOf(dt.getSoluong()));
        TextGia2.setText(String.valueOf(dt.getGia()));
        TextTong2.setText(String.valueOf(dt.Tong()));
        String valueHang=dt.getHang();
        jcHang2.setSelectedItem(valueHang);
        if(dt.getHinhanh().equals("No avatar")){
            hinhanh2.setText("No avatar");
            hinhanh2.setIcon(null);
        }
            
        
        else{
            hinhanh2.setIcon(ResizeImage(String.valueOf(dt.getHinhanh())));
        }
    }
    public DienThoai getModel(){
        DienThoai dt=new DienThoai();
        dt.setGia(Long.parseLong(TextGia2.getText()));
        dt.setHang((String)jcHang2.getSelectedItem());
        dt.setMa(TextMa2.getText());
        dt.setSoluong(Long.parseLong(TextSoLuong2.getText()));
        dt.setTen(TextTen2.getText());
        if(strHinhAnh==null){
            dt.setHinhanh("No avatar");
        }
        else{
            dt.setHinhanh(strHinhAnh);
        }
        return dt;
    }
    
    public void fillTable(){
        DefaultTableModel table=(DefaultTableModel) jtDienThoai2.getModel();
        table.setRowCount(0);
        for(DienThoai dt:list.getDienThoai()){
            Object rowjtDienThoai[]=new Object[6];
            rowjtDienThoai[0]=dt.getMa();
            rowjtDienThoai[1]=dt.getTen();
            rowjtDienThoai[3]=String.valueOf(dt.getGia());
            rowjtDienThoai[2]=dt.getHang();
            rowjtDienThoai[4]=String.valueOf(dt.getSoluong());
            rowjtDienThoai[5]=dt.getHinhanh();
        
            table.addRow(rowjtDienThoai);
        }
        
        
    }
    public boolean valiForm(){
        if(TextMa2.getText().isEmpty() || TextTen2.getText().isEmpty()
                || TextGia2.getText().isEmpty() || TextSoLuong2.getText().isEmpty()){
            return false;
        }
        return true;
    }
    
    //Ban Hang
    
    public void setGia(){
        String ten=(String)jcTen.getSelectedItem();
        for(DienThoai dt:list.getDienThoai()){
            if(dt.getTen().equals(ten))
                TextGia.setText(String.valueOf(dt.getGia()));
        }
    }
    
    
    ////Quản lý nhân viên
    
    public void resetNv(){
        TextMnv.setText("");
        TextTenNhanVien.setText("");
        TextLuong.setText("");
        TextNgaySinh.setText("");
        TextQueQuan.setText("");
        anhnhanvien.setIcon(null);
        TextSoDienThoai.setText("");
    }
    public void setModelNv(NhanVien nv){
        TextMnv.setText(nv.getMa());
        TextTenNhanVien.setText(nv.getName());
        TextLuong.setText(String.valueOf(nv.getLuong()));
        TextNgaySinh.setText(nv.getNgaysinh());
        TextQueQuan.setText(nv.getDiachi());
        jcGioiTinh.setSelectedItem((Object)nv.getGioitinh());
        TextSoDienThoai.setText(nv.getSdt());
        if(nv.getHinhanh().equals("No avatar")){
            anhnhanvien.setText("No avatar");
            anhnhanvien.setIcon(null);
        }
        
        
        else{
            anhnhanvien.setIcon(ResizeImageNv(String.valueOf(strHinhAnh)));
        }
        
    }
    public NhanVien getModelNv() throws ParseException{
        NhanVien nv=new NhanVien();
        nv.setLuong(Long.parseLong(TextLuong.getText()));
        nv.setGioitinh((String)jcGioiTinh.getSelectedItem());
        nv.setMa(TextMnv.getText());
        nv.setName(TextTenNhanVien.getText());
        nv.setNgaysinh(TextNgaySinh.getText());
        nv.setDiachi(TextQueQuan.getText());
        nv.setSdt(TextSoDienThoai.getText());
        if(strHinhAnh==null){
            nv.setHinhanh("No avatar");
        }
        else{
            nv.setHinhanh(strHinhAnh);
        }
        
        return nv;
    }
    
    public void fillTableNv(){
        DefaultTableModel table=(DefaultTableModel) jtNhanVien.getModel();
        table.setRowCount(0);
        for(NhanVien nv:listNv.getAllNhanVien()){
            Object rowjtNhanVien[]=new Object[8];
            rowjtNhanVien[0]=nv.getMa();
            rowjtNhanVien[1]=nv.getName();
            rowjtNhanVien[2]=nv.getNgaysinh();
            rowjtNhanVien[3]=nv.getDiachi();
            rowjtNhanVien[4]=nv.getGioitinh();
            rowjtNhanVien[5]=String.valueOf(nv.getLuong());
            rowjtNhanVien[6]=nv.getHinhanh();
            rowjtNhanVien[7]=nv.getSdt();
            table.addRow(rowjtNhanVien);
        }
        
        
    }
    public boolean valiFormNv(){
        if(TextMnv.getText().isEmpty() || TextTenNhanVien.getText().isEmpty()
                || TextQueQuan.getText().isEmpty() || TextLuong.getText().isEmpty()
                ||TextNgaySinh.getText().isEmpty()){
            return false;
        }
        return true;
    }
    
    
    
    //  BÁN HÀNG.
    public void resetKH(){
        TextHang.setText("");
        TextGia.setText("");
        TextSoLuong.setText("");
        TextTenKhachHang.setText("");
        TextSDT.setText("");
        TextDiaChi.setText("");
        TextTra.setText("");
        TextDu.setText("");
    }
    
    public KhachHang getModelKH(){
        KhachHang kh=new KhachHang();
        kh.setTen(TextTenKhachHang.getText());
        kh.setSdt(TextSDT.getText());
        kh.setDiachi(TextDiaChi.getText());
        kh.setTendt((String)jcTen.getSelectedItem());
        kh.setHang(TextHang.getText());
        kh.setBaohanh((String)jcBaoHanh.getSelectedItem());
        kh.setThanhtien(Long.parseLong(TextSoLuong.getText())*Long.parseLong(TextGia.getText()));
        SimpleDateFormat sd = new SimpleDateFormat("dd/MM/yyyy");
        String date=sd.format(jDate.getDate());
        kh.setThoigian(date);
        kh.setSoluong(Long.parseLong(TextSoLuong.getText()));
        return kh;
    }
    
    public void fillTableKH(){
        DefaultTableModel table=(DefaultTableModel) jtKhachHang.getModel();
        table.setRowCount(0);
        for(KhachHang kh:listKh.getAllKhachHang()){
            Object row[]=new Object[9];
            row[0]=kh.getTen();
            row[2]=kh.getSdt();
            row[1]=kh.getDiachi();
            row[3]=kh.getTendt();
            row[4]=kh.getHang();
            row[5]=kh.getBaohanh();
            row[6]=String.valueOf(kh.getThanhtien());
            row[7]=kh.getThoigian();
            row[8]=String.valueOf(kh.getSoluong());
            table.addRow(row);
        }
    }
    public void fillTableKHbyName(){
        DefaultTableModel table=(DefaultTableModel) jtKhachHang.getModel();
        table.setRowCount(0);
        for(KhachHang kh:listKh.getAllKhachHang()){
            if(kh.getTen().equals(TextNhapTen.getText())){
                Object row[]=new Object[9];
                row[0]=kh.getTen();
                row[2]=kh.getSdt();
                row[1]=kh.getDiachi();
                row[3]=kh.getTendt();
                row[4]=kh.getHang();
                row[5]=kh.getBaohanh();
                row[6]=String.valueOf(kh.getThanhtien());
                row[7]=kh.getThoigian();
                row[8]=String.valueOf(kh.getSoluong());
                table.addRow(row);
            }
        }
    }
    public void fillTableThongKe(){
        DefaultTableModel table=(DefaultTableModel) jtDoanhThu.getModel();
        table.setRowCount(0);
        for(BanHang bh:listBh.getAllBanHang()){
            Object row[]=new Object[3];
            row[0]=bh.getTen();
            row[1]=bh.getSoluong();
            row[2]=bh.getThu();
            table.addRow(row);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabMenu;
    private javax.swing.JTextField TextDiaChi;
    private javax.swing.JTextField TextDu;
    private javax.swing.JTextField TextGia;
    private javax.swing.JTextField TextGia2;
    private javax.swing.JTextField TextHang;
    private javax.swing.JTextField TextLuong;
    private javax.swing.JTextField TextMa2;
    private javax.swing.JTextField TextMnv;
    private javax.swing.JTextField TextNgaySinh;
    private javax.swing.JTextField TextNhapTen;
    private javax.swing.JTextField TextQueQuan;
    private javax.swing.JTextField TextSDT;
    private javax.swing.JTextField TextSoDienThoai;
    private javax.swing.JTextField TextSoLuong;
    private javax.swing.JTextField TextSoLuong2;
    private javax.swing.JTextField TextTen2;
    private javax.swing.JTextField TextTenKhachHang;
    private javax.swing.JTextField TextTenNhanVien;
    private javax.swing.JTextField TextTong2;
    private javax.swing.JTextField TextTra;
    private javax.swing.JLabel anhnhanvien;
    private javax.swing.JLabel hinhanh2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPBanHang;
    private javax.swing.JPanel jPCapNhat;
    private javax.swing.JPanel jPDienThoai;
    private javax.swing.JPanel jPMenu;
    private javax.swing.JPanel jPNhanVien;
    private javax.swing.JPanel jPThongKe;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbLuu;
    private javax.swing.JButton jbLuuThongTin;
    private javax.swing.JButton jbSua;
    private javax.swing.JButton jbThem;
    private javax.swing.JButton jbTim;
    private javax.swing.JButton jbTimKiem;
    private javax.swing.JButton jbXoa;
    private javax.swing.JButton jbXoaNv;
    private javax.swing.JComboBox<String> jcBaoHanh;
    private javax.swing.JComboBox<String> jcGioiTinh;
    private javax.swing.JComboBox<String> jcHang2;
    private javax.swing.JComboBox<String> jcSapXep;
    private javax.swing.JComboBox<String> jcTen;
    private javax.swing.JLabel jlThongTin;
    private javax.swing.JLabel jlTongDienThoai;
    private javax.swing.JTable jtDienThoai2;
    private javax.swing.JTable jtDoanhThu;
    private javax.swing.JTable jtKhachHang;
    private javax.swing.JTable jtNhanVien;
    private javax.swing.JButton jvSuanv;
    private com.k33ptoo.components.KButton kButton6;
    private com.k33ptoo.components.KButton kButton7;
    private com.k33ptoo.components.KButton kButton8;
    private com.k33ptoo.components.KButton kButton9;
    private keeptoo.KGradientPanel kGradientPanel2;
    private com.k33ptoo.components.KButton kbBanHang;
    private com.k33ptoo.components.KButton kbDangXuat;
    private com.k33ptoo.components.KButton kbHoaDon;
    private com.k33ptoo.components.KButton kbsanpham;
    private javax.swing.JPanel quanlydienthoai;
    private javax.swing.JLabel tlTongDoanhThu;
    // End of variables declaration//GEN-END:variables

    private void showComboHang2() {
        for(String x:listHang.getList()){
            jcHang2.addItem(x);
        }
    }


    private String showTienDu(){
       long tra=Long.parseLong(TextTra.getText());
       long gia=Long.parseLong(TextGia.getText());
       long so=Long.parseLong(TextSoLuong.getText());
       return String.valueOf(tra-gia*so);
    }


}
